// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260624214332_addCreatedAtInYoutubeVideo")]
    partial class addCreatedAtInYoutubeVideo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.Entyties.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastTrainedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RepetitionScore")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Translations")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Entyties.Subtitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("File");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("LanguageCode");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("Subtitles", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Entyties.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Entyties.YoutubeVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("YoutubeId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("YoutubeId")
                        .IsUnique();

                    b.ToTable("YoutubeVideos", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Entyties.Note", b =>
                {
                    b.HasOne("Domain.Model.Entyties.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.Model.ValueObjects.Example", "Examples", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("NoteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Text")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Translate")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("NoteId");

                            b1.ToTable("NoteExamples", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NoteId");
                        });

                    b.OwnsOne("Domain.Model.ValueObjects.Lvl", "Lvl", b1 =>
                        {
                            b1.Property<Guid>("NoteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("Lvl");

                            b1.HasKey("NoteId");

                            b1.ToTable("Notes");

                            b1.WithOwner()
                                .HasForeignKey("NoteId");
                        });

                    b.OwnsOne("Domain.Model.ValueObjects.Source", "Source", b1 =>
                        {
                            b1.Property<Guid>("NoteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<int>("Hours")
                                .HasColumnType("integer")
                                .HasColumnName("DurationContextHours");

                            b1.Property<int>("Minutes")
                                .HasColumnType("integer")
                                .HasColumnName("DurationContextMinutes");

                            b1.Property<int>("Seconds")
                                .HasColumnType("integer")
                                .HasColumnName("DurationContextSeconds");

                            b1.Property<string>("YoutubeId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("YoutubeVideoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("YoutubeVideoTitle")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("YoutubeVideoTitle");

                            b1.HasKey("NoteId");

                            b1.ToTable("Notes");

                            b1.WithOwner()
                                .HasForeignKey("NoteId");
                        });

                    b.OwnsOne("Domain.Model.ValueObjects.Transcription", "Transcription", b1 =>
                        {
                            b1.Property<Guid>("NoteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Transcription");

                            b1.HasKey("NoteId");

                            b1.ToTable("Notes");

                            b1.WithOwner()
                                .HasForeignKey("NoteId");
                        });

                    b.Navigation("Examples");

                    b.Navigation("Lvl");

                    b.Navigation("Source");

                    b.Navigation("Transcription")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Model.Entyties.Subtitle", b =>
                {
                    b.HasOne("Domain.Model.Entyties.YoutubeVideo", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Model.Entyties.User", b =>
                {
                    b.OwnsOne("Domain.Model.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email");
                });

            modelBuilder.Entity("Domain.Model.Entyties.YoutubeVideo", b =>
                {
                    b.OwnsOne("Domain.Model.ValueObjects.Duration", "Duration", b1 =>
                        {
                            b1.Property<Guid>("YoutubeVideoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Hour")
                                .HasColumnType("integer")
                                .HasColumnName("DurationHour");

                            b1.Property<int>("Minutes")
                                .HasColumnType("integer")
                                .HasColumnName("DurationMinutes");

                            b1.Property<int>("Seconds")
                                .HasColumnType("integer")
                                .HasColumnName("DurationSeconds");

                            b1.HasKey("YoutubeVideoId");

                            b1.ToTable("YoutubeVideos");

                            b1.WithOwner()
                                .HasForeignKey("YoutubeVideoId");
                        });

                    b.OwnsOne("Domain.Model.ValueObjects.LexicalComplexity", "LexicalComplexity", b1 =>
                        {
                            b1.Property<Guid>("YoutubeVideoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Complexity");

                            b1.HasKey("YoutubeVideoId");

                            b1.ToTable("YoutubeVideos");

                            b1.WithOwner()
                                .HasForeignKey("YoutubeVideoId");
                        });

                    b.Navigation("Duration")
                        .IsRequired();

                    b.Navigation("LexicalComplexity")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
